package com.alipay.authserver.domain;

import java.util.ArrayList;
import java.util.List;

public class AuthClientUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public AuthClientUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdIsNull() {
            addCriterion("auth_client_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdIsNotNull() {
            addCriterion("auth_client_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdEqualTo(Integer value) {
            addCriterion("auth_client_id =", value, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdNotEqualTo(Integer value) {
            addCriterion("auth_client_id <>", value, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdGreaterThan(Integer value) {
            addCriterion("auth_client_id >", value, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("auth_client_id >=", value, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdLessThan(Integer value) {
            addCriterion("auth_client_id <", value, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("auth_client_id <=", value, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdIn(List<Integer> values) {
            addCriterion("auth_client_id in", values, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdNotIn(List<Integer> values) {
            addCriterion("auth_client_id not in", values, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdBetween(Integer value1, Integer value2) {
            addCriterion("auth_client_id between", value1, value2, "authClientId");
            return (Criteria) this;
        }

        public Criteria andAuthClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("auth_client_id not between", value1, value2, "authClientId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdIsNull() {
            addCriterion("auth_scope_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdIsNotNull() {
            addCriterion("auth_scope_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdEqualTo(Integer value) {
            addCriterion("auth_scope_id =", value, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdNotEqualTo(Integer value) {
            addCriterion("auth_scope_id <>", value, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdGreaterThan(Integer value) {
            addCriterion("auth_scope_id >", value, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("auth_scope_id >=", value, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdLessThan(Integer value) {
            addCriterion("auth_scope_id <", value, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdLessThanOrEqualTo(Integer value) {
            addCriterion("auth_scope_id <=", value, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdIn(List<Integer> values) {
            addCriterion("auth_scope_id in", values, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdNotIn(List<Integer> values) {
            addCriterion("auth_scope_id not in", values, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdBetween(Integer value1, Integer value2) {
            addCriterion("auth_scope_id between", value1, value2, "authScopeId");
            return (Criteria) this;
        }

        public Criteria andAuthScopeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("auth_scope_id not between", value1, value2, "authScopeId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_client_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}