package com.alipay.authserver.domain;

import lombok.Builder;
import lombok.Data;

@Builder
public class AuthClientUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_client_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_client_user.auth_client_id
     *
     * @mbg.generated
     */
    private Integer authClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_client_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_client_user.auth_scope_id
     *
     * @mbg.generated
     */
    private Integer authScopeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_client_user.id
     *
     * @return the value of auth_client_user.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_client_user.id
     *
     * @param id the value for auth_client_user.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_client_user.auth_client_id
     *
     * @return the value of auth_client_user.auth_client_id
     * @mbg.generated
     */
    public Integer getAuthClientId() {
        return authClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_client_user.auth_client_id
     *
     * @param authClientId the value for auth_client_user.auth_client_id
     * @mbg.generated
     */
    public void setAuthClientId(Integer authClientId) {
        this.authClientId = authClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_client_user.user_id
     *
     * @return the value of auth_client_user.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_client_user.user_id
     *
     * @param userId the value for auth_client_user.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_client_user.auth_scope_id
     *
     * @return the value of auth_client_user.auth_scope_id
     * @mbg.generated
     */
    public Integer getAuthScopeId() {
        return authScopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_client_user.auth_scope_id
     *
     * @param authScopeId the value for auth_client_user.auth_scope_id
     * @mbg.generated
     */
    public void setAuthScopeId(Integer authScopeId) {
        this.authScopeId = authScopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authClientId=").append(authClientId);
        sb.append(", userId=").append(userId);
        sb.append(", authScopeId=").append(authScopeId);
        sb.append("]");
        return sb.toString();
    }
}