package com.alipay.authserver.domain;

import java.util.Date;
import lombok.Builder;

@Builder
public class AuthRefreshToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.token_id
     *
     * @mbg.generated
     */
    private Integer tokenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.refresh_token
     *
     * @mbg.generated
     */
    private String refreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.expires_in
     *
     * @mbg.generated
     */
    private Long expiresIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.update_user
     *
     * @mbg.generated
     */
    private Integer updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_refresh_token.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.id
     *
     * @return the value of auth_refresh_token.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.id
     *
     * @param id the value for auth_refresh_token.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.token_id
     *
     * @return the value of auth_refresh_token.token_id
     *
     * @mbg.generated
     */
    public Integer getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.token_id
     *
     * @param tokenId the value for auth_refresh_token.token_id
     *
     * @mbg.generated
     */
    public void setTokenId(Integer tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.refresh_token
     *
     * @return the value of auth_refresh_token.refresh_token
     *
     * @mbg.generated
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.refresh_token
     *
     * @param refreshToken the value for auth_refresh_token.refresh_token
     *
     * @mbg.generated
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.expires_in
     *
     * @return the value of auth_refresh_token.expires_in
     *
     * @mbg.generated
     */
    public Long getExpiresIn() {
        return expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.expires_in
     *
     * @param expiresIn the value for auth_refresh_token.expires_in
     *
     * @mbg.generated
     */
    public void setExpiresIn(Long expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.create_user
     *
     * @return the value of auth_refresh_token.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.create_user
     *
     * @param createUser the value for auth_refresh_token.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.create_time
     *
     * @return the value of auth_refresh_token.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.create_time
     *
     * @param createTime the value for auth_refresh_token.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.update_user
     *
     * @return the value of auth_refresh_token.update_user
     *
     * @mbg.generated
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.update_user
     *
     * @param updateUser the value for auth_refresh_token.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_refresh_token.update_time
     *
     * @return the value of auth_refresh_token.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_refresh_token.update_time
     *
     * @param updateTime the value for auth_refresh_token.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tokenId=").append(tokenId);
        sb.append(", refreshToken=").append(refreshToken);
        sb.append(", expiresIn=").append(expiresIn);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}