package com.alipay.authserver.dao.mapper;

import com.alipay.authserver.domain.AuthClientUser;
import com.alipay.authserver.domain.AuthClientUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AuthClientUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    long countByExample(AuthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int deleteByExample(AuthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int insert(AuthClientUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int insertSelective(AuthClientUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    List<AuthClientUser> selectByExample(AuthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    AuthClientUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthClientUser record, @Param("example") AuthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthClientUser record, @Param("example") AuthClientUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthClientUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthClientUser record);

    AuthClientUser selectByClientId(@Param("clientId") Integer clientId, @Param("userId") Integer userId);
}