package com.alipay.auth.dao.mapper;

import com.alipay.auth.domain.AuthRefreshToken;
import com.alipay.auth.domain.AuthRefreshTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthRefreshTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    long countByExample(AuthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int deleteByExample(AuthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int insert(AuthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int insertSelective(AuthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    List<AuthRefreshToken> selectByExample(AuthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    AuthRefreshToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthRefreshToken record, @Param("example") AuthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthRefreshToken record, @Param("example") AuthRefreshTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthRefreshToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_refresh_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthRefreshToken record);

    AuthRefreshToken selectByTokenId(@Param("tokenId") Integer tokenId);
}