package com.alipay.auth.dao.mapper;

import com.alipay.auth.domain.AuthClientDetails;
import com.alipay.auth.domain.AuthClientDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AuthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    long countByExample(AuthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int deleteByExample(AuthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int insert(AuthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int insertSelective(AuthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    List<AuthClientDetails> selectByExample(AuthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    AuthClientDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthClientDetails record, @Param("example") AuthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthClientDetails record, @Param("example") AuthClientDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_client_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthClientDetails record);

    /**
     * 根据clientId查询AuthClientDetails
     *
     * @param clientId string
     * @return {@link AuthClientDetails}
     */
    AuthClientDetails selectByClientId(@Param("clientId") String clientId);
}