package com.alipay.auth.dao.mapper;

import com.alipay.auth.domain.AuthAccessToken;
import com.alipay.auth.domain.AuthAccessTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    long countByExample(AuthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int deleteByExample(AuthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int insert(AuthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int insertSelective(AuthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    List<AuthAccessToken> selectByExample(AuthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    AuthAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthAccessToken record, @Param("example") AuthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthAccessToken record, @Param("example") AuthAccessTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_access_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthAccessToken record);

    AuthAccessToken selectByUserIdClientIdScope(@Param("userId") Integer userId, @Param("clientId") Integer clientId,
                                                       @Param("scope") String scope);

    AuthAccessToken selectByAccessToken(@Param("accessToken") String accessToken);
}